import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import obfuscatorPlugin from 'vite-plugin-javascript-obfuscator'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),

    // ── PWA + Workbox caching ─────────────────────────────────────────────
    // Generates a service worker that caches JS/CSS/HTML assets.
    // On repeat visits, assets load from cache (instant) instead of network.
    // Strategy: StaleWhileRevalidate — serve cache immediately, update in background.
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.ico', '*.svg', '*.png'],
      manifest: {
        name: 'Shadow System',
        short_name: 'ShadowSys',
        description: 'Solo Leveling Hunter Interface — track quests, rank up, build your shadow army.',
        theme_color: '#020408',
        background_color: '#020408',
        display: 'standalone',
        icons: []
      },
      workbox: {
        // Cache all JS, CSS, and HTML chunks generated by Vite
        globPatterns: ['**/*.{js,css,html,woff,woff2}'],
        // StaleWhileRevalidate: serve from cache immediately, fetch update in background
        runtimeCaching: [
          {
            // Google Fonts stylesheets
            urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'google-fonts-stylesheets',
              expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 }, // 1 year
            },
          },
          {
            // Google Fonts files (woff2)
            urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-webfonts',
              expiration: { maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 }, // 1 year
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // Firebase Auth & Firestore API calls — NetworkFirst (always try live data)
            urlPattern: /^https:\/\/(identitytoolkit|securetoken|firestore)\.googleapis\.com\/.*/i,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'firebase-api',
              expiration: { maxEntries: 50, maxAgeSeconds: 60 * 5 }, // 5 min fallback
              networkTimeoutSeconds: 10,
            },
          },
        ],
      },
    }),

    obfuscatorPlugin({
      include: ['src/**/*.js', 'src/**/*.jsx'],
      exclude: [/node_modules/],
      apply: 'build',
      debugger: true,
      options: {
        compact: true,
        controlFlowFlattening: false,
        deadCodeInjection: false,
        stringArray: true,
        stringArrayEncoding: ['base64'],
        stringArrayThreshold: 0.5,
        transformObjectKeys: false,
      }
    })
  ],

  build: {
    sourcemap: false,
    // ── Manual chunk splitting ─────────────────────────────────────────────
    // Breaks the single bundle into smaller cached chunks.
    // Returning users only re-download the chunk that changed, not everything.
    rollupOptions: {
      output: {
        manualChunks: {
          // React core + framer-motion (rarely changes)
          'vendor': ['react', 'react-dom', 'framer-motion'],
          // Firebase SDK (large, rarely changes)
          'firebase': ['firebase/app', 'firebase/auth', 'firebase/firestore', 'firebase/functions'],
          // Zustand store
          'state': ['zustand'],
        }
      }
    }
  },

  // ── Dev proxy: routes /api/openrouter → openrouter.ai server-side ──
  // Bypasses ad blockers & CORS since the HTTP call is made by Node, not the browser
  server: {
    proxy: {
      '/api/openrouter': {
        target: 'https://openrouter.ai/api/v1',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api\/openrouter/, ''),
        secure: true,
      }
    }
  }
})

